#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x8e,0x5d,0x86,0x3f,0x07,0x11,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x8e,0x5d,0x86,0x3f,0x07,0x75,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
